name: SimpleAlert
options:
  bundleIdPrefix: com.shotastage
deploymentTarget: "12.0"
attributes:
  ORGANIZATIONNAME: "Shota Shimazu"

targets:
  SimpleAlert:
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    sources: SimpleAlert
    settings:
      CURRENT_PROJECT_VERSION: 1
